version: '3.8'
services:
    iebt_api:
        container_name: iebt_api
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - iebt

    iebt_nginx:
        container_name: iebt_nginx
        image: nginx:1.23.3-alpine
        restart: unless-stopped
        ports:
            - ${APP_PORT}:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - iebt

    iebt_db:
        container_name: iebt_db
        image: mariadb:10.10
        restart: unless-stopped
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - ./.docker/database:/var/lib/mysql
        ports:
            - ${DB_PORT}:3306
        networks:
            - iebt

    iebt_composer:
        container_name: iebt_composer
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: composer
        working_dir: /app
        volumes:
            - ./:/app
        command: composer install


networks:
    iebt:
        driver: bridge

